### ISSUE TITLE
@1x support

### ISSUE THREAD

**Issue by munsonbh** [schwa23/cleanupsfui#1]
+1 for support for 1x

**Comment by talkaboutdesign** [comment]
+1 for same

**Comment by jordaniusrex** [comment]
Yeah for 1x!

**Comment by philworthy** [comment]
+1 this (@1x) would be amazingly useful. thanks!

**Comment by iamsankalp** [comment]
@schwa23 Hey! I was working on getting this up for @1x based on your script only. I'm not really great at code and wanted your help in 2 things - 

1) I reckon you have used polynomial regression for generating tracking values for font-sizes not mentioned by Apple. How do i generate a better regression formula with new x,y inputs of 1x values?

2) Apple recommends interpolating values. Is it same as polynomial regression?

Thanks,
Sankalp

**Comment by gnyrd** [comment]
+1

C'mon.. it's time to adopt @1x for design work. Really.

**Comment by schwa23** [comment]
@iamsankalp 1) The formulas shouldn't change; it _should_ be just a matter of multiplying the input by 2, then dividing the output by 2. For 2) I actually tried to do a linear interpolation at first, but the polynomial regression turned out to be easier, and for 99% of the usage the results are the same.

**Comment by schwa23** [comment]
FYI if anyone is reading this, just updated the plugin with 1x support. let me know if you have any problems with it.

**Comment by iamsankalp** [comment]
@schwa23 Thanks for replying and update, Joshua! :)
